# https://dev.azure.com/home-assistant

parameters:
  ignoreDev: false
  pythonVersion: '3.7'

jobs:
- job: 'VersionValidate'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.pythonVersion }}'
    inputs:
      versionSpec: '${{ parameters.pythonVersion }}'
  - script: |
      setup_version="$(python setup.py -V)"
      branch_version="$(Build.SourceBranchName)"

      if [ "${{ parameters.ignoreDev }}" == "true"" ] && [ "${branch_version}" == "dev" ]; then
        exit 0
      elif [ "${setup_version}" != "${branch_version}" ]; then
        echo "Version of tag ${branch_version} don't match with ${setup_version}!"
        exit 1
      fi
    displayName: 'Check version of branch/tag'
